name: Build

on:
    push:
        branches:
            - master

jobs:
    build_electron:
        name: Build Electron App
        runs-on: macos-14

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Extract version number from commit message
              id: extract_version
              run: |
                  VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
                  if [ -z "$VERSION" ]; then
                      echo "Commit message does not contain a version number. Skipping build."
                      exit 1
                  fi
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.11.0'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Update version in package.json
              run: |
                  sed -i.bak "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
                  cat package.json

            - name: Build Windows and macOS Apps
              run: npm run build:all
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create and Publish GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.VERSION }}
                  name: Release ${{ env.VERSION }}
                  draft: false
                  prerelease: false
                  files: |
                      build/*.dmg
                      build/*.exe
                      build/*.blockmap
                      build/latest.yml
                      build/latest-mac.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}